### ISSUE TITLE
"Type de vue" retourne toujours à "Maj." (skin Estuary)

### ISSUE THREAD

**Issue by franckgaga** [dualB/plugin.video.telequebec#10]
En naviguant dans l'addiciel Tele-Quebec, peu importe le type de vue que je sélectionne dans les options de visualisation, il retourne toujours à "Maj." (Vue latérale avec en-tête descriptif). Ce type de vue n'est pas très pratique pour une grande liste de tous les épisodes...

Libreelec 9.0.1 sur RPi 3B+

**Comment by dualB** [comment]
Quelle est la demande ici?

**Comment by franckgaga** [comment]
Que l'addiciel se souvienne du type de vue sélectionné dans les répertoires si possible ? Il me semble que c'était le cas dans le passé (veille version de l'addiciel/Kodi 17 peut-être ?)...

Si ce n'est pas possible, je recommanderais une autre vue par défaut. Soit les vues de type "Mur" ou "Liste". C'est plus pratique pour naviguer au travers d'une grande quantité d’élément (émission avec beaucoup d'épisode par exemple)

Merci !

**Comment by franckgaga** [comment]
Aussi, ça vient avec un autre bug mineur : l'ordre de classement switch entre décroissant et croissant en se promenant dans le menu.  
Ex : Dans "Magazines" -> "L'indice Mc$sween"
1. Type de vue à : Maj, ordre Décroissant
2. Ouvrir "Épisode 45"
3. Naviguer au répertoire précédant
4. Type de vue à : Maj. ordre Croissant
5. Changer type de vue à : Liste large ordre Décroissant
5. Ouvrir "Épisode 45"
6. Naviguer au répertoire précédant
7. Type de vue à : Maj. ordre Croissant
8. etc.
C'est certain que c'est pas un gros bug. Mais quand on recherche un épisode en les ouvrant un à un pour regarder leur contenu ça vient assez mêlant (l'épisode plus récent est à gauche, après à droite, après à gauche, etc...)
Merci pour l'excellent addon !

**Comment by dualB** [comment]
J'ai retiré le classement automatique qui était fautif, prévu pour la version 3.3.0.
