### ISSUE TITLE
Les nouvelles vidéos ne ce joue pas

### ISSUE THREAD

**Issue by Europe57** [dualB/plugin.video.telequebec#13]
Bonjour,

Les nouvelles vidéos saison 2020 ne ce joue pas sur l'addiciel.

Exemple :  De gardes 24/7 - Épisode 001 - Covid, le calme avant la tempête (premier épisode de la saison 6), ce joue pas, les anciens épisodes jouent.

**Comment by dualB** [comment]
Ici ça joue. As-tu la version la plus récente installée (3.3.0)?
Que dit le fichier kodi.log?

**Comment by Europe57** [comment]
Ah oui! Désolé du dérangement, mais y a 2 jours quand j'avais essayé, impossible de lire la vidéo.

Un soucis peut être chez moi y a 2 jours.

Merci pour ton extension, des années que je l'utilise pour voir de superbe émission/documentaire.

**Comment by dualB** [comment]
Donc j'en comprends que le problème s'est réglé?

**Comment by Europe57** [comment]
Oui, la vidéo ce lit maintenant.
