### ISSUE TITLE
Lien non disponible

### ISSUE THREAD

**Issue by lefou66** [dualB/plugin.video.telequebec#14]
Ça fait quelques jours que j'ai des liens non disponible dans la section pour enfants et pourtant direct sur le site ils fonctionnent..jsuis avec Kodi 18.7 sur une berline gt1 mini

**Comment by dualB** [comment]
As-tu des exemples de liens non disponibles?
Que dit le fichier kodi.log?

**Comment by lefou66** [comment]
Par exemple ,la plupart des Simon ou houa houa...pour les log j'vais regarder plus tard.Jai essayé de réinstaller le dépôt QC aussi

**Comment by dualB** [comment]
Assure-toi d'avoir la version la plus récente 3.3.0 de TQ.

**Comment by lefou66** [comment]
C'est ce que j'ai

**Comment by lefou66** [comment]
Jai regardé sur le site de télé QC et comme exemple ..Simon ep52 fonctionne mais dans le addon...comment je fait pour t'envoyer les logs,j'vois pas l'option dans le addon?

**Comment by boucchar** [comment]
Bonjour, je confirme que j'ai le même problème que lefou66. J'ai essayé La Pat Patrouille et Passe-Partout sans succès. Voici la partie de log de l'erreur. Merci pour ton travail en passant.
[log.txt](https://github.com/dualB/plugin.video.telequebec/files/5215340/log.txt)

**Comment by jfsimoneau** [comment]
J'ai remarqué que la liste des streams dans `getURI`, que ce soit `Limelight` ou `Brightcove`, ont un champ `canPlay`. Les vidéos que j'essaie de jouer (la Pat Patrouille) ont à la fois `Limelight` et `Brightcove`, mais la source `Limelight` a le champ `canPlay` à `false` alors que la source `Brightcove` a le champ `canPlay` à `true`.

J'ai essayé de changer `getURI` comme suit, mais ça ne joue toujours pas.
```
def getURI(video_json,refID):
    streams = video_json['streamInfos']
    for stream in streams:
        if stream['source']=='Limelight' and stream['canPlay']:
            return m3u8LL(refID)
        elif stream['source']=='Brightcove' and stream['canPlay']:
            return m3u8BC(stream['sourceId'])
```

Ça va plus loin dans les logs, par contre.
```
2020-09-14 13:14:43.321 T:1937203776  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.telequebec/?url=https%3A%2F%2Fzonevideo.telequebec.tv%2Fmedia%2F31107&sourceId=26768943a34
24a38b1e2f76582573528
2020-09-14 13:14:43.753 T:1512043392  NOTICE: Creating InputStream
2020-09-14 13:14:44.253 T:1512043392  NOTICE: Creating Demuxer
2020-09-14 13:14:44.276 T:1512043392   ERROR: Open - error probing input format, https://ssaiplayback.prod.boltdns.net/playback/once/v1/dash/live-timeline/clear/6150020952001/dcd6de
5f-a864-4ef6-b416-dcdc4f4af216/4cfa8b7b-6365-4ee7-9a0a-c25e7fc0b890/bd09b309-d910-4cc8-8137-51fa395ccf93/manifest.mpd?bc_token=NWY2MDAxNjdfNDQyNGQ1MDNjNGM5YjhmNzdjZDhjZDIwMjQ1NmFmNG
FhMTc4MzBiYzRmMjkxMDEzMzkwNzZmMGI2NDk2OWQ3YQ%3D%3D&window.location.href=%7Bwindow.location.href%7D&window.location.href=%7Bwindow.location.href%7D
2020-09-14 13:14:44.276 T:1512043392   ERROR: OpenDemuxStream - Error creating demuxer
2020-09-14 13:14:44.276 T:1512043392  NOTICE: CVideoPlayer::OnExit()
2020-09-14 13:14:44.391 T:1937203776  NOTICE: CVideoPlayer::CloseFile()
2020-09-14 13:14:44.392 T:1937203776  NOTICE: VideoPlayer: waiting for threads to exit
2020-09-14 13:14:44.392 T:1937203776  NOTICE: VideoPlayer: finished waiting
```

J'espère que ça peut aider un peu.

**Comment by mbelang** [comment]
Même chose ici

**Comment by BastienFR** [comment]
Moi aussi j'ai un message comme quoi aucun lien n'est accessible.  Dans mon cas, je suis sur CoreElec, et tout mes addons sont à jours.

**Comment by dualB** [comment]
Les liens Limelight semblent en voie d'être dépréciés. Mais les liens BrightCove ne sont pas encore 100% fonctionnels.
Je vais voir ce que je peux trouver..

**Comment by dualB** [comment]
La nouvelle version de TQ 3.4.0 va abandonner Limelight et seulement offrir les liens Brightcove. Tout semble redevenu fonctionnel après ce correctif.

**Comment by dualB** [comment]
Vous pouvez mettre à jour l'additiel.

**Comment by lefou66** [comment]
Parfait merci pour ton travail!
