### ISSUE TITLE
The stream loaded is very low quality (fix detailed bellow)

### ISSUE THREAD

**Issue by andreq** [dualB/plugin.video.telequebec#4]
I've changed some code in jouer_video from navig.py so it would load the stream from Tele-Quebec new API instead of the old (flash?) API.

I kept all the stream info to minimize changes, but all my code is doing is getting the m3u8 playlist and find the better a stream (same code you were doing, but using the new api). It then find the m3u8 "chunks" playlist which I feed directly to kodi. It plays the chunks playlist like a full video!

Here's the full mehod :

```
def jouer_video(media_uid):
    """ function docstring """
    check_for_internet_connection()
    
    # Obtenir JSON avec liens RTMP du playlistService
    video_json = simplejson.loads(\
        cache.get_cached_content(\
            'http://production.ps.delve.cust.lldns.net/r/PlaylistService/media/%s/getPlaylistByMediaId' % media_uid\
        )\
    )
    
    # Preparer list de videos à jouer
    playlist = xbmc.PlayList(xbmc.PLAYLIST_VIDEO)
    playlist.clear()

    play_list_item =video_json['playlistItems'][0]
    
    video_m3u8 = m3u8.load('https://mnmedias.api.telequebec.tv/m3u8/' + play_list_item['refId'] + '.m3u8')
    
    # Analyser chaque stream disponible pour trouver la meilleure qualité

    highest_bit_rate = 0
    stream_url = None
    for stream in video_m3u8.playlists:
        if stream.stream_info.bandwidth > highest_bit_rate:
            highest_bit_rate = stream.stream_info.bandwidth
            stream_url = stream.uri
    if stream_url:
        url_final = stream_url 
       # log('Starting playback of :' + urllib.quote_plus(url_final))
        item = xbmcgui.ListItem(\
            video_json['title'],\
            iconImage=video_json['imageUrl'],\
            thumbnailImage=play_list_item['thumbnailImageUrl'], path=url_final)
        #playlist.add(url_final, item)
        play_item = xbmcgui.ListItem(path=url_final)
        xbmc.log("**************************************DING? " +sys.argv[0])
        xbmcplugin.setResolvedUrl(__handle__,True, item)
        xbmc.log("**************************************DONG! ")
    else:
        xbmc.executebuiltin('Notification(%s,Incapable d''obtenir lien du video,5000,%s' % (ADDON_NAME, ADDON_ICON))

    #if playlist.size() > 0:
    #    xbmc.Player(xbmc.PLAYER_CORE_DVDPLAYER).play(playlist)
```

NOTE : You also need to add m3u8 addon dependency into your addon.xml :
add `<import addon="script.module.m3u8" version="0.2.2"/>` after line 11

m3u8 addon is in official kodi repo so it should download automatically.

I haven't used GITHub enough to suggests a pull request, I'm quite sorry for posting the "raw code" in here.

Edit : I speak french btw

**Comment by dualB** [comment]
La dépendance à m3u8, elle est possible depuis quelle version de Kodi?

**Comment by andreq** [comment]
http://kodi.wiki/view/Add-on:M3u8  Kodi 15 supposément. J'ai gossé un peu avec mon build OpenElec sur OrangePi, mais si j'arrive le faire fonctionner avec ça, c'est surement bon pour tlm. 

OpenElec sur OrangePi ça tien avec de la broche, mais c'est fonctionnel :P

**Comment by dualB** [comment]
La dépendance à m3u8 ne doit pas nécessiter d'installation à bras, ça doit se faire directement. Pour l'instant, ca ne fonctionne pas chez nous, je poursuis mes essais.

**Comment by andreq** [comment]
La version est peut-etre 0.2.10 pour m3u8, j'ai pris un vieux Zip et le repo avais un mise a jours.

**Comment by dualB** [comment]
Je vais faire ma propre routine de scan de la liste m3u8, c'est plus safe pour la fonctionnalité tout azimut.
Je dépose d'ici demain la version finale.

**Comment by andreq** [comment]
Sounds good to me, je voulais seulement faire qqchose de rapide.

**Comment by dualB** [comment]
J'ai fait un nouveau release, svp l'installer manuellement et le tester, je le pousserai ensuite sur DépotQuébec. Merci!
