### ISSUE TITLE
Le contenu HD est joué en SD

### ISSUE THREAD

**Issue by rogerpoo** [dualB/plugin.video.telequebec#6]
Bonjour,
Après que la version 3.0.2 ait cessé de fonctionner complètement, j'ai téléchargé et installé la version 3.1.0. Le contenu fonctionne, mais en SD plutôt qu'en HD.

Merci d'avance!

**Comment by dualB** [comment]
Ça prendrait plus de détails (quel(s) contenu(s), à quel moment, est-ce reproductible?).

**Comment by rogerpoo** [comment]
Bonjour,
Tout le contenu s'affiche en SD alors qu'il était en HD avec la version 3.0.2. J'ai essayé autant les émissions jeunesse que des documentaires. 
Oui c'est reproductible. 
J'ai désinstallé et réinstallé à 3 reprises sans succès.

Merci.

**Comment by rogerpoo** [comment]
Suis-je le seul à avoir tout le contenu en SD? Si tel est le cas, y a-t-il un moyen de complètement désintaller l'add-on pour éliminer cette possibilité?

**Comment by dualB** [comment]
Le mieux serait de désinstaller aussi Dépôt-Québec (ou s'il n'est pas installé, de l'utiliser pour s'assurer d'avoir la version la plus à jour de TQ). Quelle version de Kodi utilises-tu?
