### ISSUE TITLE
Deux hommes en ors et francs tireur ne sort pas de contenu

### ISSUE THREAD

**Issue by dlevesque1980** [dualB/plugin.video.telequebec#9]
Cette fin de semaine j’essaie de regarder deux hommes en or ou les franc tireur mais je n’ai plus rien dans la liste des videos. Je suis sur kodi 18 version android

**Comment by dualB** [comment]
Bonjour Didier, 
Pour l'instant, le même constat vaut également sur le site de Télé-Québec, certaines émissions ne présentent soudainement plus aucun contenu (exemple : https://zonevideo.telequebec.tv/a-z/54/deux-hommes-en-or) . 
Puisque le problème vient de leur côté, on doit attendre et voir comment évolue la situation dans les prochaines heures.

**Comment by dlevesque1980** [comment]
Ok merci

**Comment by dualB** [comment]
C'est revenu, problème disparu.
